export const MOODS = [
  {
    id: 'calm',
    label: 'CALM',
    tagline: 'places where time slows down',
    emoji: '😌',
    dot: '#7aab90',
    grad: ['#c8ddd0', '#6b8f5e'],
    color: '#6B8F5E',
  },
  {
    id: 'aesthetic',
    label: 'AESTHETIC',
    tagline: 'spaces worth standing still for',
    emoji: '✨',
    dot: '#b09ac0',
    grad: ['#e0d0ec', '#b09ac0'],
    color: '#b09ac0',
  },
  {
    id: 'energetic',
    label: 'ENERGETIC',
    tagline: 'buzzing rooms, loud tables',
    emoji: '🔥',
    dot: '#d4834a',
    grad: ['#f0d8c0', '#e8c4a0'],
    color: '#d4834a',
  },
  {
    id: 'social',
    label: 'SOCIAL',
    tagline: 'made for staying too long',
    emoji: '👥',
    dot: '#c9a66b',
    grad: ['#f0e0c0', '#e8d4a8'],
    color: '#C9A66B',
  },
  {
    id: 'focus',
    label: 'FOCUS',
    tagline: 'quiet enough to think clearly',
    emoji: '💻',
    dot: '#7a9ab0',
    grad: ['#c8d8e8', '#7a9ab0'],
    color: '#7a9ab0',
  },
  {
    id: 'romantic',
    label: 'ROMANTIC',
    tagline: 'dim lights & close tables',
    emoji: '❤️',
    dot: '#c07a8a',
    grad: ['#f0d0d8', '#c07a8a'],
    color: '#c07a8a',
  },
  {
    id: 'explore',
    label: 'EXPLORE',
    tagline: 'off the algorithm, on foot',
    emoji: '🌍',
    dot: '#6aaa98',
    grad: ['#c8e0d8', '#6aaa98'],
    color: '#6aaa98',
  },
  {
    id: 'budget_chill',
    label: 'CHILL',
    tagline: 'good time, easy bill',
    emoji: '💸',
    dot: '#a0a868',
    grad: ['#d8dcc0', '#a0a868'],
    color: '#a0a868',
  },
];
