"""add_google_place_id_and_city_index

Revision ID: ad649d49e98e
Revises: 7bc8c9a97734
Create Date: 2026-04-26 11:24:13.986346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad649d49e98e'
down_revision: Union[str, None] = '7bc8c9a97734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('google_place_id', sa.String(length=200), nullable=True))
    op.create_index('ix_places_city_id', 'places', ['city_id'], unique=False)
    op.create_unique_constraint(None, 'places', ['google_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='unique')
    op.drop_index('ix_places_city_id', table_name='places')
    op.drop_column('places', 'google_place_id')
    # ### end Alembic commands ###
