"""add_neighborhood

Revision ID: d7251e2cbfb4
Revises: 4dbe04220916
Create Date: 2026-04-26 15:21:40.674829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7251e2cbfb4'
down_revision: Union[str, None] = '4dbe04220916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'neighborhood')
    # ### end Alembic commands ###
