"""add_user_auth_fields

Revision ID: db2a3290f66a
Revises: ad649d49e98e
Create Date: 2026-04-26 11:38:54.460917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2a3290f66a'
down_revision: Union[str, None] = 'ad649d49e98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
